## Home Assignment 4

Submit your solution via Moodle until 23.59pm on Wednesday, January 22nd. Late submissions are accepted for 12 hours following the deadline, with 1/3 of the total possible points deducted from the score.

Submit your solutions in teams of up 2-3 members. **Single student submissions will not be graded anymore**.
Please denote all members of the team with their student ID and full name in the notebook. In this home assignment, you only have to submit a .ipynb notebook. Do not submit anything else than this file!

Cite ALL your sources for coding this home assignment. In case of plagiarism (copying solutions from other teams or from the internet) ALL team members will be expelled from the course without warning.

##### List team members, including all student IDs here:
1. Student 1 (123456)
2. Student 2 (123457)
3. (optional) Student 3 (123458)

In [1]:
import numpy as np
import networkx as nx

### Task 1: Robustness Attacks (2 pts)


#### a) Random Attacks (0.5 pts)

Implement a function that performs a random attack of deleting $n$ nodes on a given graph. Use the signature in the cell below.

In [56]:
# INPUT VALUES
# G: networkx Graph
# n: number of deleted nodes
# 
# return G without deleted nodes

def random_attack(G,n):
    #your code here

#### b) Targeted Attacks  (0.5 pts)

Implement a function that performs a targeted attack of deleting the $n$ highest-degree nodes on a given graph. Use the signature in the cell below.

In [20]:
# INPUT VALUES
# G: networkx Graph
# n: number of deleted nodes
#
# return G without deleted nodes

def target_attack(G,n):
    # your code here

#### c) Attacking Empirical and Random Graphs (1 pt)

Create an Erdos-Renyi and a Barabasi-Albert graph with 1000 nodes and average degree 2.

For both graphs and attack types, conduct 50 consecutive attacks of removing 10 nodes, and plot the number of removed nodes against the share of the biggest connected component in the graph. For each graph, include the curves of both attacks in the same plot. What do you observe?

###  Task 2: Schelling's Model of Segregation            (3 pts)

In this task we implement a simulation of Schelling's model of segregation.  
A concise explanation on how the model is specified as well as another simulation can, for instance, be found here:

http://nifty.stanford.edu/2014/mccown-schelling-model-segregation/

#### a) Grid creation (0.25 pts)
Using the signature in the cell below, write a function that returns a numpy array of the given shape (rows, columns). Cells with a red agent should be marked with the value 1, cells with a blue agent with value 2, empty cells with a 0.

In [14]:
# INPUT VALUES:
# shape: integer tuple, shape of grid
# share_red: percent share of red nodes in the data
# share_blue: percent share of blue nodes in the data 
# -> note that blue+red shares should be <1 aas empty cell are needed

import random

def create_grid (shape, share_red, share_blue):
    # your code here
    shape_x = shape[0]
    shape_y = shape[1]
    tmap = np.zeros((shape_x,shape_y))
    num_red = shape_x*shape_y*share_red
    num_blue = shape_x*shape_y*share_blue
    
    while(num_red != 0):
        p_x = random.randint(0, shape_x-1)
        p_y = random.randint(0, shape_y-1)
        if tmap[p_x,p_y] == 0:
            tmap[p_x,p_y] = 1
            num_red = num_red-1
            
    while(num_blue != 0):
        p_x = random.randint(0, shape_x-1)
        p_y = random.randint(0, shape_y-1)
        if tmap[p_x,p_y] == 0:
            tmap[p_x,p_y] = 2
            num_blue = num_blue-1
            
    print(tmap)
    
create_grid((60,70),0.5,0.3)

[[1. 2. 0. ... 2. 1. 1.]
 [1. 1. 2. ... 1. 1. 2.]
 [2. 2. 0. ... 1. 1. 0.]
 ...
 [1. 1. 1. ... 2. 0. 1.]
 [1. 2. 1. ... 1. 1. 1.]
 [1. 0. 0. ... 1. 0. 2.]]


#### b) Visualization (0.25 pts)

Write a function that takes a numpy grid and plots it. We recommend to use matplotlib for this

In [ ]:
# grid: 2D numpy array
import matplotlib.pyplot as plt
plt.ion()
plt.figure()

def visualize(grid):
    # your code here

#### c) Simulating the model (1.5 pts)

Write a function that performs a full simulation of Schelling's model given a specific initial state, by performing steps until the maximum number of steps is reached or there was no change for the given amount of steps. Every n_viz steps, as well as at the very end, a visualization of the model should be plotted.
Use a model where in case that a particular agent is unhappy, he moves a to a randomly chosen vacant place.

In [ ]:
# INPUT VALUES: 
# grid: initial grid to start simulation with (2D numpy array)
# pp: preferred poportion of neighbors of own class
# n_max: maximum number of iteration steps
# no_changes_steps: number of simulation steps after which one has to stop if no change in the grid occurs
# n_viz: number of iteration steps after which current state is plotted

# RETURN:
# final_grid: 2D numpy array representing the grid at the end of your simulation

def simulate(grid, preferred_proportion, n_max, no_changes_steps, n_viz):
    # your code here
    return final_grid

#### d) Model Extension (1 pt)

Adaptt your functions such that they support multiple groups (instead of just red and blue), and each group can have a separate preferred proportion. Use the signatures from the cells below, where changes from the signatures in 2c) are explained.

In [ ]:
# shares: list of shares for each color, entries in return matrix from 0 (empty cell) to number of colors.
def create_grid_ext(shape, shares):
    # your code here

In [ ]:
# adapt color selection
def visualize_ext(grid):
# your code here

In [ ]:
# preferred_proportions: give a list of preferred proportions for each color
def simulate_ext(grid, preferred_proportion, max_steps, no_changes_steps, iterations_to_next_vizualization):
    # your coder here